# Generated by Django 4.2.1 on 2023-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idCard', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
